// This code calculate and plot the Pt broadening using the histograms generated by Integration.cpp
// It can be compile with
// g++ -Wall -fPIC -I./include `root-config --cflags` Broadening.cpp -o ./bin/Broadening  `root-config --glibs` ./include/Broad.h

#include "Broad.h"

int main(){

  TStopwatch t;

  TString inputDirectory  = "/home/matias/proyecto/MoreEnergy/Data/";
  TString plotDirectory   = "/home/matias/proyecto/MoreEnergy/Plots/";


  PtBroadeningFullIntegrated(inputDirectory, plotDirectory);

  PtbroadeningMultiZh(inputDirectory, plotDirectory);

  PtBroadeningVarIntegrated(cQ2, inputDirectory, plotDirectory);
  PtBroadeningVarIntegrated(cNu, inputDirectory, plotDirectory);
  PtBroadeningVarIntegrated(cZh, inputDirectory, plotDirectory);
  t.Print();

}
